### ISSUE TITLE
Update compiler version and dependency versions in Aztec contract example

### ISSUE THREAD

**Issue by jzaki** [microbecode/zk-languages#3]
Examples uses [0.18.0](https://github.com/microbecode/zk-languages/blob/master/noir/contract/contracts/Nargo.toml#L4)
Latest Noir release at [0.33.0](https://noir-lang.org/docs/) at the time of writing.

**Comment by microbecode** [comment]
Thanks for the poke!
This is actually pending for my question in the Noir Discord: https://discord.com/channels/1113924620781883405/1275797432365482044/1280761732478013441

I kind of gave up on it, as nobody responded, and decided to try later somewhere in the future.

**Comment by microbecode** [comment]
After some discussions and support, I finally got both the stand-alone and contract usage working. Thanks to all Aztec people for the help.

The Noir examples have been updated ot use version 0.35.0.
